language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'ppa:beineri/opt-qt-5.10.1-trusty'
    packages:
    - dpkg
    - qt510base
    - cmake
    - git
    - libcurl4-openssl-dev
    - librsvg2-bin
    - libfuse-dev
    - desktop-file-utils

notifications:
  email: false


script:
  - /opt/qt510/bin/qt510-env.sh
  - export QT_SELECT=qt5
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release .
  - make
  - DESTDIR=AppDir make install
  - ./linuxdeploy-x86_64.AppImage --init-appdir --appdir=AppDir
  - ./linuxdeploy-plugin-appimage-x86_64.AppImage --appdir=AppDir

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
  - bash upload.sh AppImage*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/